version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: apache
    group: apache
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 300
      runas: root
