name: Terraform Plan and Cost Analysis

on:
  pull_request:
    branches:
      - main

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

jobs:
  terraform:
    name: terraform plan
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changed Terraform files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.tf
            **/*.tfvars

      - name: Set working directory
        id: set-working-dir
        run: |
          if [ -z "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            echo "No Terraform files changed"
            exit 1
          fi

          # Get unique directories from all changed Terraform files
          UNIQUE_DIRS=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs -n1 dirname | sort -u)
          DIRS_COUNT=$(echo "$UNIQUE_DIRS" | wc -l)

          if [ "$DIRS_COUNT" -gt 1 ]; then
            echo "Multiple Terraform directories changed:"
            echo "$UNIQUE_DIRS"
            echo "Error: Changes must be limited to a single Terraform directory"
            exit 1
          fi

          WORKING_DIR=$UNIQUE_DIRS
          echo "working_dir=$WORKING_DIR" >> $GITHUB_OUTPUT
          echo "Found Terraform changes in directory: $WORKING_DIR"

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-duration-seconds: 900
          role-session-name: GitHubActionsTerraformCICD

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5

      - name: Terraform Format
        id: fmt
        working-directory: ${{ steps.set-working-dir.outputs.working_dir }}
        run: terraform fmt -recursive -check=true

      - name: Terraform Initialize
        id: init
        working-directory: ${{ steps.set-working-dir.outputs.working_dir }}
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: ${{ steps.set-working-dir.outputs.working_dir }}
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ${{ steps.set-working-dir.outputs.working_dir }}
        run: terraform plan -no-color

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ steps.set-working-dir.outputs.working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform plan
        working-directory: ${{ steps.set-working-dir.outputs.working_dir }}
        run: terraform plan -out tfplan.binary

      - name: Terraform show
        working-directory: ${{ steps.set-working-dir.outputs.working_dir }}
        run: terraform show -json tfplan.binary > plan.json

      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        working-directory: ${{ steps.set-working-dir.outputs.working_dir }}
        run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json

      - name: Post Infracost comment
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: update
