openapi: 3.0.1
info:
  title: Example API
  description: API Gateway with AWS Lambda
  version: 1.0.0

paths:
  /cost-confirmation:
    get:
      summary: Cost Confirmation
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  month:
                    type: string
                  cost:
                    type: float
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        credentials: ${iam_role_arn}
        uri: ${cost_confirmation_invoke_arn}
        passthroughBehavior: when_no_match
        responses:
          default:
            statusCode: "200"
